//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.19 at 03:10:39 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fusesource.com/training/payment", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package jaxB;
